# Об авторе

С 2007 года изучал различные IT-направления по разработке Web-сайтов и Видео-презентаций, а позже (с 2010 года) стал выполнять работы на заказ на фрилансе.

В целом программирование для меня не только сфера деятельности, но также и моё хобби по жизни. Я активно слежу за трендами, люблю учиться новому и совершенствовать свои навыки в целом. На текущий момент я учусь в GeekBrains (gb.ru) на специализацию: "ИT-инженер. Передовые технологии".

## Технические навыки:

—Фронтенд-разработка: JavaScript (продвинутый уровень), HTML5, CSS3, React.js, AngularJS.  
—Бэкенд-разработка: Node.js, Express.js, MongoDB, MySQL, RESTful API.  
—Веб-дизайн: Adobe Dreamweaver (продвинутый уровень), Adobe Fireworks, Adobe Photoshop (любая версия), Adobe Illustrator (любая версия), CorelDRAW (по необходимости).  
—Интеграция и управление контентом: 1С-Битрикс (включая CRM и интеграции), OpenCart, CS-Cart, Webasyst, Joomla, Wordpress, MotoCMS.  
—Разработка видео-контента: Adobe Premiere Pro, Adobe After Effects, DAZ 3D Studio (для работы с VR-контентом).  
—Инструменты разработки: Visual Studio Code (VS Code), Notepad++, GIT (GitHub, GitLab).  
—Проектирование и организация процессов: Notion.  

## Дополнительные навыки:

—Управление проектами: Agile/Scrum методологии, Trello, Jira.  
—Бухгалтерский учёт, подготовка отчётности, документооборот в сервисах "Моё Дело" и "Контур. Эльба" (и другие).

Кроме того отлично справляюсь с любой работой по наполнению контентом (карточки товаров для интернет-магазинов, написание уникальных SEO-ориентированных статей по различным тематикам и многое другое).

И помимо перечисленного имею большой опыт просто работы в команде (в т.ч. в большом коллективе), умею эффективно коммуницировать и обосновывать свои решения (там, где это действительно уместно). Кроме того со своей стороны готов быстро погружаться в текущие задачи и новые технологии.

***

## Моё портфолио:  
https://motoyama.one

Также мой аккаунт GitHub:  
https://github.com/DAYIAWAN

***

## Мои приложения:
1. Готовый телефонный справочник, разработанный на Python  
https://github.com/DAYIAWAN/Course-at-GB/tree/main/myCourses/1___FinalTask___2023

2. Готовое приложение бронирования столиков в сети из трёх ресторанов (на выбор клиента), реализованное на Java  
https://github.com/DAYIAWAN/Course-at-GB/tree/main/myCourses/2___FinalTask___2023

3. Готовое приложение для Агентства по поиску вакансий, реализованное на Java через шаблон проектирования "Singleton"  
https://github.com/DAYIAWAN/Course-at-GB/tree/main/myCourses/3___FinalTask___2023

4. Консольное приложение заметок, реализованное на Python  
https://github.com/DAYIAWAN/Course-at-GB/tree/main/myCourses/4___FinalTask___2023

5. Консольное приложение магазина игрушек, реализованное на Java  
https://github.com/DAYIAWAN/Course-at-GB/tree/main/myCourses/5___FinalTask___2023

6. Простой и удобный телеграм-бот для продажи товаров и услуг (Python)  
https://t.me/MOTOYAMA_bot

***

/С уважением,  
Дайяван/
